title: Keith Van Norstrand # your name (or website title) here
logo: "images/KVN_1 thumbnail.gif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with experience in relational databases, Microsoft Excel,
  SQL, R Programming and Tableau.
  <br><br>
  I'm a level 20 bard. I like to sing and love a good story. 
  Whether it's telling one or hearing one. I've always loved the connection that's made. 
  I have a beautiful wife, and wild 4 year old daughter who help build my story every day. 
  I like to roll the dice and take a chance.   
  <br><br>
  <a href="https://www.linkedin.com/in/krvan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-247292368-1 # your Google Analytics tracking ID here
