title: Keith Van Norstrand # your name (or website title) here
logo: "images/KVN_1 thumbnail.gif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/krvan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-247292368-1 # your Google Analytics tracking ID here
